query IndexQuery {
  allImageSharp {
    edges {
      node {
        ... on ImageSharp {
          resize(width: 125, height: 125, rotate: 180) {
            src
          }
        }
      }
    }
  }
  sizes: imageSharp(id: { regex: "/fecolormatrix-kanye-west.jpg/" }) {
    sizes(
      duotone: { highlight: "#f00e2e", shadow: "#192550" }
      traceSVG: {
        color: "#f00e2e"
        turnPolicy: TURNPOLICY_MINORITY
        blackOnWhite: false
      }
      toFormat: PNG
    ) {
      ...GatsbyImageSharpSizes_tracedSVG
    }
  }
  sizesDuotone: imageSharp(id: { regex: "/fecolormatrix-kanye-west.jpg/" }) {
    sizes(
      maxWidth: 120
      duotone: { highlight: "#0ec4f1", shadow: "#192550" }
      traceSVG: { color: "#1E2151" }
    ) {
      ...GatsbyImageSharpSizes_tracedSVG
    }
  }
  sizesDuotone50: imageSharp(id: { regex: "/fecolormatrix-kanye-west.jpg/" }) {
    sizes(
      maxWidth: 120
      duotone: { highlight: "#0ec4f1", shadow: "#192550", opacity: 50 }
      traceSVG: { color: "#A7DEF6" }
    ) {
      ...GatsbyImageSharpSizes_tracedSVG
    }
  }
  sizesDuotone75: imageSharp(id: { regex: "/fecolormatrix-kanye-west.jpg/" }) {
    sizes(
      maxWidth: 120
      duotone: { highlight: "#0ec4f1", shadow: "#192550", opacity: 75 }
      traceSVG: { color: "#0ec4f1" }
    ) {
      ...GatsbyImageSharpSizes_tracedSVG
    }
  }
  sizesDuotone25: imageSharp(id: { regex: "/fecolormatrix-kanye-west.jpg/" }) {
    sizes(
      maxWidth: 120
      traceSVG: { color: "#D1EFFB" }
      duotone: { highlight: "#0ec4f1", shadow: "#192550", opacity: 25 }
    ) {
      ...GatsbyImageSharpSizes_tracedSVG
    }
  }
  sizesDuotoneOriginal: imageSharp(
    id: { regex: "/fecolormatrix-kanye-west.jpg/" }
  ) {
    sizes(maxWidth: 120, traceSVG: { color: "#e7f7fe" }, toFormat: PNG) {
      ...GatsbyImageSharpSizes_tracedSVG
    }
  }
  resolution: imageSharp(id: { regex: "/lol.jpg/" }) {
    resolutions(grayscale: true, width: 500) {
      ...GatsbyImageSharpResolutions_withWebp
    }
  }
  cropDefault: imageSharp(id: { regex: "/gatsby.jpg/" }) {
    resize(width: 180, height: 180) {
      src
    }
  }
  cropBottomLeft: imageSharp(id: { regex: "/nyancat/" }) {
    resize(width: 180, height: 180, cropFocus: SOUTHWEST) {
      src
    }
  }
  cropEntropy: imageSharp(id: { regex: "/gatsby.jpg/" }) {
    resize(width: 180, height: 180, cropFocus: ENTROPY) {
      src
    }
  }
  cropCenter: imageSharp(id: { regex: "/gatsby.jpg/" }) {
    resize(width: 180, height: 180, cropFocus: CENTER) {
      src
    }
  }
}

query IndexQuery {
  allImageSharp {
    edges {
      node {
        ... on ImageSharp {
          resize(width: 125, height: 125, rotate: 180) {
            src
          }
        }
      }
    }
  }
  sizes: imageSharp(id: { regex: "/background-wood.jpg/" }) {
    sizes(toFormat: JPG) {
      ...GatsbyImageSharpSizes
    }
  }
}








query Portfolio {
    allJsFrontmatter(filter: {data: {pageSlug: {eq: "/portfolio"}}}) {
      edges {
        node {
          data {
            pageTitle
            pageSubtitle
            pageSlug
            headerTitle
            headerBody
            headerImage
            pageSections {
              workTitle
              workSubtitle
              workImage
              workTags
            }
            error
          }
        }
      }
    }
  }
  }
    heroCode: imageSharp(id: { regex: "/heroCode.png/" }) {
      sizes(maxWidth: 1600) {
        ...GatsbyImageSharpSizes
      }
    }
    logos: allImageSharp(filter: { id: { regex: "/skills/" } }) {
      edges {
        node {
          sizes(maxWidth: 480, quality: 80) {
            ...GatsbyImageSharpSizes
          }
        }
      }
    }
    logoSignature: imageSharp(id: { regex: "/logoSignature/" }) {
      sizes(maxWidth: 480) {
        ...GatsbyImageSharpSizes
      }
    }
    footerTypewriter: imageSharp(id: { regex: "footer/typewriter/" }) {
      sizes(maxWidth: 480) {
        ...GatsbyImageSharpSizes
      }
    }
    social: imageSharp(id: { regex: "/footer/social/" }) {
      sizes(maxWidth: 359) {
        ...GatsbyImageSharpSizes
      }
    }
  }