{
  allImageSharp {
    edges {
      node {
        ... on ImageSharp {
          resize(width: 150, height: 150, grayscale: true) {
            src
          }
        }
      }
    }
  }
}

{
  allImageSharp(id: /Users/aslezak/dev/sandbox/aslezak-gatsby/src/images/background-wood.jpg) {
    edges {
      node {
        id
      }
    }
  }
}



      id: { regex: "/fecolormatrix-kanye-west.jpg/" }
